service: TwitterPickupy

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs4.3
  stage: production
  region: ap-northeast-1
  environment:
    TWITTER_CONSUMER_KEY: ${env:TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${env:TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN_KEY: ${env:TWITTER_ACCESS_TOKEN_KEY}
    TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET}
    LINE_CHANNEL_ACCESS_TOKEN: ${env:LINE_CHANNEL_ACCESS_TOKEN}

package:
#  include:
#    - include-me.js
#    - include-me-dir/**
  exclude:
    - .git
    - .envrc

functions:
  twitter:
    handler: handler.twitter
    events:
      - http:
          method: get
          path: twitter
  line:
    handler: handler.line
    events:
      - http:
          method: post
          path: line
